[package]
name = "redust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rstest = "0.18.1"
redis = "0.23.2"
